language: php
sudo: false
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || return 0

install:
  - travis_retry composer install --no-progress --prefer-dist
  - travis_retry composer create-project --no-interaction jakub-onderka/php-parallel-lint /tmp/php-parallel-lint

script:
  - php /tmp/php-parallel-lint/parallel-lint.php -e php,phpt --exclude vendor .
  - ./vendor/bin/tester -s -p php --colors 1 -C ./tests/KdybyTests

after_failure:
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - env: title="Lowest Dependencies 5.6"
      php: 5.6
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - ./vendor/bin/tester -s -p php --colors 1 -C ./tests/KdybyTests

    - stage: Test Coverage
      php: 7.1
      script:
        - ./vendor/bin/tester -s -p phpdbg --colors 1 -C --coverage ./coverage.xml --coverage-src ./src ./tests/KdybyTests
      after_script:
        - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        - php php-coveralls.phar --verbose --config tests/.coveralls.yml

    - stage: Outdated Dependencies
      php: 7.1
      script:
        - composer outdated --direct --strict

  allow_failures:
    - stage: Test Coverage
    - stage: Outdated Dependencies
